# Generated by Django 4.2.7 on 2023-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('outdoor_number', models.IntegerField()),
                ('indoor_number', models.IntegerField(blank=True, null=True)),
                ('street2', models.CharField(max_length=100)),
                ('street3', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(default='Veracruz', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
